### ISSUE TITLE
You loose ability to stream when converting from AMP to PSR response

### ISSUE THREAD

**Issue by roelvanduijnhoven** [amphp/http-client-psr7#12]
If you try to convert an AMP response with a stream, into a PSR response. The stream will be read, and then set on the PSR response. So if you convert, you will loose the ability to actually stream content from a response real-time.

This behaviour can be seen in `PsrAdapter::copyToPsrStream`.

Is there a way around this? Or a way we can improve this? I'd be willing to help here, but could not figure this out myself!

**Comment by kelunik** [comment]
This is something that can't be addressed in the Amp v2 version, but can be addressed in the Amp v3 version.

**Comment by roelvanduijnhoven** [comment]
This bridge library is build upon Amp v3. So, do you think @kelunik , that it should be possible to properly implement streaming in this library? Would you have some pointers or psuedo code? I tried to tackle it already, but failed to do so. Thanks! :pray:
